### ISSUE TITLE
Unhandled Exception: System.IO.IOException: Not a directory

### ISSUE THREAD

**Issue by pmcao** [microsoft/verisol#119]
Please help running regressions. 

I followed instructions to run the regressions on Ubuntu Linux 18.04 and have successfully built verisol with all dependencies. However, the last step (running regressions) failed and has a core dump. It looks like a config problem.

The trace and verisol directory tree are attached.

Thanks.

```
~/verisol 
dotnet $VeriSolPath/Sources/SolToBoogieTest/bin/Debug/netcoreapp2.2/SolToBoogieTest.dll $VeriSolPath/corral/bin/Debug/corral.exe $VeriSolPath

Warning!!! only running tests that have a prefix /root/verisol....

Unhandled Exception: System.IO.IOException: Not a directory
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path)
   at SolToBoogieTest.RegressionExecutor.BatchExecute() in /root/verisol/Sources/SolToBoogieTest/RegressionExecutor.cs:line 50
   at SolToBoogieTest.Program.Main(String[] args) in /root/verisol/Sources/SolToBoogieTest/Program.cs:line 42
[1]    83736 abort (core dumped)  dotnet  $VeriSolPath/corral/bin/Debug/corral.exe $VeriSolPath


echo $VeriSolPath
/root/verisol

# uname -rvim
4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64

# cat /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

# dotnet --version
2.2.300

# ./corral/bin/Debug/corral.exe --version

Usage error: Unknown command line argument: --version
Usage: cba fname [Flags]

-------------------------------------------------------------
Flags:
 /k:int             	 Sets execution context bound
 /main:str          	 Sets main procedure name
 /recursionBound:int	 Set recursion depth bound
 /trackAllVars      	 Track all shared variables.
 /track:str         	 Track variable str.
 /useArrayTheory    	 Use native array theory for z3.
                    	 (This doesn't allow user-defined types.)
 /timeLimit:n       	 Set Z3 timeout to n sec (default 500)
 /flags:file        	 Read flags from file.
 /printBoogieExt 	 Prints language extensions made to Boogie

-------------------------------------------------------------

# ./corral/bin/Debug/z3.exe --help
Z3 [version 4.8.4 - 64 bit - build hashcode d6df51951f4c]. (C) Copyright 2006-2016 Microsoft Corp.

```
[tree.txt](https://github.com/microsoft/verisol/files/3239609/tree.txt)

**Comment by shuvendu-lahiri** [comment]
@Yuepeng-Wang @rongpan can you repro this on linux?

**Comment by pmcao** [comment]
Same problem on macOS as well, @rongpan and I repro'd today. Seems like a config issue.

**Comment by rongpan** [comment]
yes, I have checked with @pmcao about this issue. Right now some configurations for build / regression test need to be fixed under Linux / OSX, will work on it.

**Comment by shuvendu-lahiri** [comment]
@pmcao is this issue not resolved in the latest master? If so, can you please close it? Also, I notice you use $VeriSolPath which should be expanded to the complete actual path of VeriSol root folder.

**Comment by pmcao** [comment]
It works now. Thanks!

**Comment by WinterPlum** [comment]
The corral binary cannot be found correctly on Linux machines, because the path is case sensitive. The repository uses lower case path "corral/bin/debug/corral.exe" by default, but the program uses "Corral/bin/debug/Corral.exe".

**Comment by Yuepeng-Wang** [comment]
The corral binary cannot be found correctly on Linux machines, because the path is case sensitive. The repository uses lower case path "corral/bin/debug/corral.exe" by default, but the program uses "Corral/bin/debug/Corral.exe".

**Comment by shuvendu-lahiri** [comment]
Verified on Windows. 

@rongpan can you run regressions on Mac? If not, reopen the issue.

**Comment by rongpan** [comment]
Verified on Mac. All regressions passed.

**Comment by locpv-ibl** [comment]
Verified on Ubuntu 16.04. All regressions passed. But I don't know how to test a vulnerable smart contract haha
