### ISSUE TITLE
Assertion failure in SolToBoogie ProcedureTranslator.cs

### ISSUE THREAD

**Issue by rongpan** [Microsoft/verisol#12]
Debug.Assert(currentStmtList != null);
fails in TranslateStatement()

**Comment by shuvendu-lahiri** [comment]
@rongpan can you please provide a complete example that can repro this error?

**Comment by rongpan** [comment]
[0x5f401a460fc931a7e6d4141188501f3b91ed1a95.txt](https://github.com/Microsoft/verisol/files/2780609/0x5f401a460fc931a7e6d4141188501f3b91ed1a95.txt)
(change file extension to .sol)

**Comment by shuvendu-lahiri** [comment]
@rongpan what was the rootcause for this issue, also, can you reference the commit/PR that fixes  and what is the regression example?
