### ISSUE TITLE
corral/bin/Debug/corral.exe not found

### ISSUE THREAD

**Issue by locpv-ibl** [microsoft/verisol#123]
I'm trying to install verisol to my Ubuntu machine. I've installed all needed libraries, sources and so on. 

In the end, when I execute the command

```dotnet $VeriSolPath/Sources/SolToBoogieTest/bin/Debug/netcoreapp2.2/SolToBoogieTest.dll $VeriSolPath $VeriSolPath/Test```

it returns me this error:

> /home/phanvanloc/verisol/Corral/bin/debug/Corral.exe /recursionBound:8 /k:1 /main:CorralEntry_IncDec __SolToBoogieTest_out.bpl
Error: Cannot open assembly '/home/phanvanloc/verisol/Corral/bin/debug/Corral.exe': No such file or directory.

**Comment by shuvendu-lahiri** [comment]
#122 has fixed this issue. Can you try again and close this if resolved. I hope you have a Corral.exe in /home/phanvanloc/verisol/corral/bin/debug/corral.exe.
