### ISSUE TITLE
Unknown form of function call

### ISSUE THREAD

**Issue by rongpan** [Microsoft/verisol#14]
Unhandled Exception: System.SystemException: Unknown form of function call expr: uint256/address
   at SolToBoogie.TransUtils.GetFuncNameFromFuncCallExpr(Expression expr)

Examples:
uint8 public decimals = 18;
...
totalSupply = 200000000 * 10 ** uint256(decimals);

_transfer (msg.sender, address(this), totalSupply);
...
function _transfer(address _from, address _to, uint _value) internal {

**Comment by shuvendu-lahiri** [comment]
@rongpan can you please provide a complete example that can repro this error?

**Comment by rongpan** [comment]
[0xf6317dd9b04097a9e7b016cd23dcaa7cfe19d9c6.txt](https://github.com/Microsoft/verisol/files/2780578/0xf6317dd9b04097a9e7b016cd23dcaa7cfe19d9c6.txt)
(change file extension to .sol)

**Comment by shuvendu-lahiri** [comment]
Closed via #29
