### ISSUE TITLE
Dump Boogie/SMT-LIB

### ISSUE THREAD

**Issue by yoni206** [microsoft/verisol#217]
Is there a way to dump the Boogie / SMT-LIB intermediate files that are generated by VeriSol?

**Comment by shuvendu-lahiri** [comment]
When you run VeriSol, there is a file **__SolToBoogieTest_out.bpl** that is generated in the same folder. 
```
dotnet d:\verisol\bin\debug\verisol.dll Error.sol AssertFalse
```
