### ISSUE TITLE
Type Modifier Translation Error

### ISSUE THREAD

**Issue by stephensj2** [microsoft/verisol#237]
It appears that annotating variable types with required modifiers such as payable affect VeriSol's ability to find functions. When trying to translate the function transferOwnership in the file given below, VeriSol fails with the following message:

VeriSol translation error: File , Line -1, Contract Ownable, Function transferOwnership:: Cannot find a function with signature: _transferOwnership(address)

The specified function does appear in the file, however it has type _transferOwnership(address payable). It should be noted that the variable used to call _transferOwnership is also of type address payable.

[Ownable.txt](https://github.com/microsoft/verisol/files/4130257/Ownable.txt)

**Comment by shuvendu-lahiri** [comment]
closing.
