### ISSUE TITLE
Inline assembly is not implemented

### ISSUE THREAD

**Issue by ellab123** [microsoft/verisol#242]
The test below generates translation error:

```
contract AssemblyTest
{
	bool b;
	int x;
    constructor () public {
  }
	
function foo() public {
		b = bar(x);
		if (!b)
			assert(false);
	}
function bar(int x) public returns (bool) { 
	uint256 size;
	assembly { size := x }
	return size > 0;
	}
}
```

**Comment by shuvendu-lahiri** [comment]
We stub out the body of the method where inline assembly is present, so it is a non-deterministic method. Users can write further specifications in Boogie level.

**Comment by shuvendu-lahiri** [comment]
"With this feature a function that contains an inline assembly is translated into a procedure with no implementation, which generates a non-deterministic result. Related regression test is Assembly1.sol." from #243
