### ISSUE TITLE
Locals in Modifier

### ISSUE THREAD

**Issue by stephensj2** [microsoft/verisol#248]
Currently VeriSol does not support defining locals in modifiers. There are some contracts that rely on defining a local in the modifier, such as the Re-entrancy guard contract given here:

[ReentrancyGuard.txt](https://github.com/microsoft/verisol/files/4459200/ReentrancyGuard.txt)

**Comment by shuvendu-lahiri** [comment]
Example is [ModifierLocal.sol](https://github.com/microsoft/verisol/blob/master/Test/regressions/ModifierLocal.sol)
