### ISSUE TITLE
VeriSol Calldata translation

### ISSUE THREAD

**Issue by stephensj2** [microsoft/verisol#249]
Sometimes when processing functions whose arguments have storage location calldata, VeriSol crashes with the following error:
`VeriSol translation error: Unknown type string during InferKeyTypeFromTypeString: address[] calldata`
An example of such is given below:
[calldata.txt](https://github.com/microsoft/verisol/files/4459221/calldata.txt)

**Comment by shuvendu-lahiri** [comment]
Please let me know if it is OK to close this.

**Comment by stephensj2** [comment]
It seems to work. I think it can be closed.
