### ISSUE TITLE
...a reference guide draft or similar to ease defining and integrating proofs?

### ISSUE THREAD

**Issue by syscoopco** [microsoft/verisol#259]
Which is the best public resource, such as a reference guide draft, that eases to formally construct the specification of my smart contract aiming to verify it by means of VeriSol?

No Azure user. I'm using the typical truffle suite configuration.

Thanks.

**Comment by shuvendu-lahiri** [comment]
A reference guide is something that we hope to get sometime soon. 

Meanwhile, the best resources are  https://github.com/microsoft/verisol/blob/master/INSTALL.md#running-verisol to see examples of various specification constructs.

**Comment by syscoopco** [comment]
Got it.
