### ISSUE TITLE
Question: what does the json file do in the config directory? Can I specify the options of verisol in the .sol file?

### ISSUE THREAD

**Issue by gaobo89** [microsoft/verisol#271]
As titled: 

what does the json file do in the config directory? 
Can I specify the options of verisol in the .sol file?

Is assertion statement a must in solidity source-code when check overflow with verisol?

Thanks a lot!

**Comment by shuvendu-lahiri** [comment]
The json file in test\config\ folder is purely for consumption of the tool that runs regressions. VeriSol takes its input in the command line.
