### ISSUE TITLE
Is this still going to be maintained?

### ISSUE THREAD

**Issue by solauditor** [microsoft/verisol#273]
I want to use VeriSol and Celestial, but they don't seem to be maintained. Can anyone from the team comment?

**Comment by shuvendu-lahiri** [comment]
VeriSol is unfortunately not actively maintained at this time. We may get back on the project at a future date. 

Adding @suvamM for Celestial.

**Comment by solauditor** [comment]
Maybe @samvid25 can comment too?

**Comment by suvamM** [comment]
@solauditor Unfortunately, the status is the same for Celestial. It is not under active development or maintenance. However, Celestial does come with a lot of documentation and samples for the existing features. If you get stuck, you can contact @samvid25 and me, and we can try to unblock you.

**Comment by solauditor** [comment]
Thank you for the support @suvamM! I really appreciate that. Thank you as well @shuvendu-lahiri!
