### ISSUE TITLE
Support for unsigned values

### ISSUE THREAD

**Issue by shuvendu-lahiri** [microsoft/verisol#6]
VeriSol does not model that unsigned values are non-negative. This can lead to false alarms.

**Comment by shuvendu-lahiri** [comment]
Lets add an assume (t >= 0) for any variable (including temporaries) of type unsigned.

**Comment by garbervetsky** [comment]
So, there are two competing options: 
1) Add assume (t>=0) to variables (parameters, returns, state variables, temporaries). In the examples posted in [Zeppelin forum](https://forum.openzeppelin.com/t/using-automatic-analysis-tools-with-makerdao-contracts/1021) we manually applied that approach. 
2) Add assume (t>=0) to translated sub expressions. Implies less code changes and make sure that all sub expression are addressed. May lead to code bloat

I will try first approach 2.

**Comment by shuvendu-lahiri** [comment]
Closing this until we find another issue.
