### ISSUE TITLE
Need support for integer constant for function argument

### ISSUE THREAD

**Issue by cs0317** [microsoft/verisol#64]
In the following code, foo(1) causes an exception in InferFunctionSignature because the type "int_const 1" is not supported.

```
pragma solidity ^0.4.24;
contract PublicPreviewMembers {
    constructor() public {      
          bool tmp= foo(1);  
    }

    function foo(uint x) internal returns (bool) {
           return true;
   }
}
```

**Comment by cs0317** [comment]
duplicate of #61

**Comment by shuvendu-lahiri** [comment]
Also, the callsite does not indicate that the argument type of foo. The AST infers the function type as foo(int), which does not match foo(uint), the definition.

**Comment by shuvendu-lahiri** [comment]
tracking duplicate #86.
