### ISSUE TITLE
Missing information about Dependencies folder

### ISSUE THREAD

**Issue by garbervetsky** [Microsoft/verisol#81]
The script setup_windows.cmd and run_verisol_win.cmd refer to a folder VERISOL_DEPENDENCIES_DIR which seems to be "\verisol_dependencies\". 
However, there is no such folder in the repository and no information about what files should be included there.

**Comment by shuvendu-lahiri** [comment]
This script is not officially supported...only used as a helper for some tasks and is likely to change frequently. So we decided not to document it for users. https://github.com/Microsoft/verisol/blob/master/INSTALL.md has the more detailed instructions.
