### ISSUE TITLE
Dependencies as git submodules

### ISSUE THREAD

**Issue by garbervetsky** [microsoft/verisol#83]
To make installation and maintenance easier, it would be recommendable to include the project dependencies (i.e., Boogie, Corral, etc) as git submodules. It is important that each submodule refers to the the last commit that has been tested for this tool.

**Comment by shuvendu-lahiri** [comment]
@garbervetsky OK to close this issue? Please test it out and let me know if the instructions need update for Linux.

**Comment by garbervetsky** [comment]
I can check it on Mac OSX, not in Linux :-)

**Comment by shuvendu-lahiri** [comment]
sure, OSX is fine. At least on one additional platform :-)

**Comment by garbervetsky** [comment]
> sure, OSX is fine. At least on one additional platform :-)

Done for OSX. Very similar to Linux.
