### ISSUE TITLE
Struct constructor not recognized in invocation

### ISSUE THREAD

**Issue by garbervetsky** [Microsoft/verisol#87]
Related with #76. 

When a constructor is called in an invocation it is recognized as a function invocation rather that a call to a constructor.

`
   pragma solidity ^0.4.24;

   contract StructConstructorInvoke {
    S[] ss;
    S s;
    struct S {
        uint x;
        uint y;
        string z;
    }

    function testStructConstructor() public {
        ss.push(S(22, 33, "abc")); // Here is the problem
        s = ss[0];
        assert (s.x == 22);
        assert (s.y == 33);
    }
}
`

**Comment by shuvendu-lahiri** [comment]
@garbervetsky try the fix and close the issue.

**Comment by garbervetsky** [comment]
@shuvendu-lahiri I tried the fix and it works well.
