### ISSUE TITLE
Call to abi function fails

### ISSUE THREAD

**Issue by garbervetsky** [Microsoft/verisol#89]
The use of function in the `abi` interface fail by throwing an exception in the method `GetASTNodeById` as the keyword `abi` does not exist. 

`
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException()
...
.\verisol\Sources\SolToBoogie\TranslatorContext.cs:line 114
`

Example:

`    function abiCall(uint256 x, uint256 y) public pure returns(bytes) {
        bytes memory encoded = abi.encodePacked(x, y);
        return encoded;
    }
`

**Comment by shuvendu-lahiri** [comment]
@garbervetsky added a regression above. Please close this if this suffices for now.

**Comment by garbervetsky** [comment]
@shuvendu-lahiri if I do `c = keccak256(abi.encodePacked(a, b))` I'm still getting the same error. 
I have to do `bytes memory aux = abi.encodePacked(a, b); c = keccak256(aux);` but this seems to be a more general issues related with composition of functions.

**Comment by garbervetsky** [comment]
@shuvendu-lahiri still failing with this example: 

```  
pragma solidity ^0.4.24;
 library abiSample {
    function useAbi2(uint256 a, uint256 b) public pure returns(bytes32) {
         bytes32 h = keccak256(abi.encodePacked(a, b));
         return h;
     }
    function useAbi1(uint256 a) public pure  returns(bytes32) {
         bytes32 h = keccak256(abi.encodePacked(a));
         return h;
      }
}
```

throws this exception:
```
FailFast: Unknown id: 45
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at SolToBoogie.TranslatorContext.GetASTNodeById(Int32 id) in 
 .\verisol\Sources\SolToBoogie\TranslatorContext.cs:line 113
   at SolToBoogie.ProcedureTranslator.IsExternalFunctionCall(FunctionCall node) in .\verisol\Sources\SolToBoogie\ProcedureTranslator.cs:line 1618
```

**Comment by shuvendu-lahiri** [comment]
Please try master branch again.

**Comment by garbervetsky** [comment]
Great! Fixed!
